server:
  port: ${PORT:6080}

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa

  h2:
    console:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1005699460275-5lj3s3e6bemht5tks42l96qiv7stts51.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

jwt:
  issuer: dydrnxke@gmail.com
  secret_key: blog-project